spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smsdb
    username: smsuser
    password: smspass
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  jackson:
    default-property-inclusion: non_null

server:
  port: 8080

app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration: 86400000